// Minimal env shim for extension build
export const env = {
    NEXT_PUBLIC_APP_URL: "http://localhost:3000",
    NEXT_PUBLIC_TURNSTILE_SITE_KEY: "",

    NEXT_PUBLIC_PUSHER_APP_ID: "a2e0706c-2033-4d09-a728-cb67389cfc46",
    NEXT_PUBLIC_PUSHER_APP_KEY: "765cf238-0d71-4fa6-b213-63da76522c53",
    NEXT_PUBLIC_PUSHER_APP_HOST: "localhost",
    NEXT_PUBLIC_PUSHER_APP_PORT: "6011",
    NEXT_PUBLIC_PUSHER_APP_TLS: false,

    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "",
    NEXT_PUBLIC_STRIPE_PREMIUM_PRODUCT_ID: "",
    NEXT_PUBLIC_STRIPE_PREMIUM_MONTHLY_PRICE_ID: "",
    NEXT_PUBLIC_STRIPE_PREMIUM_YEARLY_PRICE_ID: "",
};
