services:
    app:
        container_name: cryptex-vault-web
        environment:
            NODE_ENV: "production"
            DATABASE_URL: ${DATABASE_URL}
            NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
            NEXTAUTH_URL: ${NEXTAUTH_URL}
            UPSTASH_REDIS_REST_URL: ${UPSTASH_REDIS_REST_URL}
            UPSTASH_REDIS_REST_TOKEN: ${UPSTASH_REDIS_REST_TOKEN}
            TURNSTILE_SECRET: ${TURNSTILE_SECRET}
            INFOBIP_BASE_URL: ${INFOBIP_BASE_URL}
            INFOBIP_API_KEY: ${INFOBIP_API_KEY}
            EMAIL_SENDER: ${EMAIL_SENDER}
            EMAIL_CONTACT_US_SENDER: ${EMAIL_CONTACT_US_SENDER}
            EMAIL_CONTACT_US_RECEIVER: ${EMAIL_CONTACT_US_RECEIVER}
            PUSHER_APP_SECRET: ${PUSHER_APP_SECRET}
            STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
            STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
            _BREAK: 1
            NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
            NEXT_PUBLIC_TURNSTILE_SITE_KEY: ${NEXT_PUBLIC_TURNSTILE_SITE_KEY}
            NEXT_PUBLIC_PUSHER_APP_ID: ${NEXT_PUBLIC_PUSHER_APP_ID}
            NEXT_PUBLIC_PUSHER_APP_KEY: ${NEXT_PUBLIC_PUSHER_APP_KEY}
            NEXT_PUBLIC_PUSHER_APP_HOST: ${NEXT_PUBLIC_PUSHER_APP_HOST}
            NEXT_PUBLIC_PUSHER_APP_PORT: ${NEXT_PUBLIC_PUSHER_APP_PORT}
            NEXT_PUBLIC_PUSHER_APP_TLS: ${NEXT_PUBLIC_PUSHER_APP_TLS}
            NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
            NEXT_PUBLIC_STRIPE_PREMIUM_PRODUCT_ID: ${NEXT_PUBLIC_STRIPE_PREMIUM_PRODUCT_ID}
            NEXT_PUBLIC_STRIPE_PREMIUM_MONTHLY_PRICE_ID: ${NEXT_PUBLIC_STRIPE_PREMIUM_MONTHLY_PRICE_ID}
            NEXT_PUBLIC_STRIPE_PREMIUM_YEARLY_PRICE_ID: ${NEXT_PUBLIC_STRIPE_PREMIUM_YEARLY_PRICE_ID}
        build:
            context: ./
            dockerfile: ./web/prod.Dockerfile
        restart: always
        ports:
            - 3000:3000
